# Generated by Django 5.0.6 on 2024-07-20 17:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ALIHF_reg", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebinarSurveys",
            fields=[
                (
                    "survey_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("survey_title", models.CharField(max_length=100)),
                ("accepting_response", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now=True)),
                ("link", models.URLField()),
            ],
            options={
                "verbose_name_plural": "Webinar Surveys",
                "db_table": "Webinar Surveys",
            },
        ),
    ]
