# Generated by Django 5.0.7 on 2024-11-26 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ALIHF_basic', '0004_webinarvideos_webinar_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('poll_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('poll_title', models.CharField(max_length=100)),
                ('accepting_response', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('link', models.URLField()),
                ('frame_link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Polls',
                'db_table': 'Polls',
            },
        ),
    ]
