# Generated by Django 5.0.4 on 2024-04-04 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ALIHF_auth", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="phone", new_name="phone_number",
        ),
    ]
