# Generated by Django 5.0.6 on 2024-06-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ALIHF_auth", "0003_rename_phone_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_type", models.CharField(max_length=7)),
            ],
            options={
                "verbose_name_plural": "Registration Types",
                "db_table": "Registration Type",
            },
        ),
    ]
