# Generated by Django 5.0.6 on 2024-06-19 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ALIHF_auth", "0004_registrationtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationtype",
            name="creation_type",
            field=models.CharField(max_length=100),
        ),
    ]
