# Generated by Django 5.0.6 on 2024-06-19 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ALIHF_auth", "0005_alter_registrationtype_creation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ALIHF_auth.registrationtype",
            ),
            preserve_default=False,
        ),
    ]
