# Generated by Django 5.0.6 on 2024-06-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ALIHF_auth", "0006_user_registration_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="registration_type",),
        migrations.DeleteModel(name="RegistrationType",),
    ]
